apiVersion: v1
kind: Service
metadata:
  name: webapp-deployment
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # Esto por default es ClusterIP
  type: NodePort